[general]
import = ["~/.config/alacritty/city-lights.toml"]

[env]
WINIT_X11_SCALE_FACTOR = ".81"
LANGUAGE = "en_US"

[window]
opacity = 0.875
padding = {x = 10, y = 5}
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal = {family = "Monaco", style = "Regular"}
bold = {family = "Monaco", style = "Bold"}
size = 15.0
offset = { x = 0, y = 0}
glyph_offset = { x = 0, y = 0}

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Block", blinking = "Always"}

[[hints.enabled]]
hyperlinks = false
regex = "(https://|http://)"
command = "open"
