#!/bin/bash

[ -z "$PS1" ] && return

# If `id` returns zero, you’re root. Be red.
if [ $(id -u) -eq 0 ];then 
	# you are root, set red color prompt
	export PS1="\[\033[1;31m\][\u@\h \W]\\$ \[\033[0m\]"
else # normal
	export PS1="\[\033[1;33m\][\u@\h \W]\\$ \[\033[0m\]"
fi

# Load bash_completion (brew install bash_completion)
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# History
export HISTSIZE=10000; # 10,000 lines of history is MORE than enough
export HISTFILESIZE=$HISTSIZE;
export HISTIGNORE="ls:exit:date:history:* --help:* -h"; # ignore unhelpful for time travelling.

# Color the shell
export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# Always use color output for `ls`
alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

export LESS_TERMCAP_md=$(tput bold; tput setaf 3); # Highlight section titles in man pages

export MANPAGER="less -X"; # Don't clear the screen after quitting `man`

# Language
# this may not be portable in my work environment! Commented by default.
# Prefer US English and use UTF-8
#export LANG="en_US.UTF-8"
#export LC_ALL="en_US.UTF-8"

# Add `~/bin` to `$PATH`
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# Add tab completion for `defaults`
complete -W "NSGlobalDomain" defaults;

# Load grc from brew, if it exists (brew install grc)
if [ -f $(brew --prefix)/etc/grc.bash ]; then
        . $(brew --prefix)/etc/grc.bash
fi
